#undef STK
#undef PUSH
#undef POP
#undef ARG1
#undef ARG2
#undef ARG3
#undef HAVE_ARGS
#undef NO_ARGS
#undef HAVE_ONE_ARG
#undef HAVE_TWO_ARGS
#undef HAVE_THREE_ARGS
#undef FOR_EACH_ARG
#undef JMP
#undef BP
#undef INV_ERROR
#undef RAM
#undef IF
#undef THEN
#undef ELSE
#undef BYTE_IND
